const flights = [
  {
    id: 22,
    flightNumber: "a123",
    departure: "israel",
    landing: "thailand",
    numOfSeats: 52,
    departureTime: "17:00 pm",
    landingTime: "07:00 am",
    isFirstClass: true,
  },
  {
    id: 23,
    flightNumber: "b123",
    departure: "amsterdam",
    landing: "tel aviv",
    numOfSeats: 52,
    departureTime: "14:00 pm",
    landingTime: "18:00 pm",
    isFirstClass: true,
  },
  {
    id: 24,
    flightNumber: "c746",
    departure: "berlin",
    landing: "addis abeba",
    numOfSeats: 52,
    departureTime: "15:00 pm",
    landingTime: "03:00 am",
    isFirstClass: false,
  },
  {
    id: 25,
    flightNumber: "c456",
    departure: "new york",
    landing: "kingston",
    numOfSeats: 52,
    departureTime: "22:00 pm",
    landingTime: "11:00 am",
    isFirstClass: false,
  },
];
module.exports = flights
